target = r"C:\Users\沙银\Documents\Codex\2026-07-21\sanfangx-piliotto-https-github-com-sanfangx\repo\lib\utils\download.dart"
content = []
content.append("import 'dart:io';")
content.append("import 'dart:typed_data';")
content.append("")
content.append("import 'package:device_info_plus/device_info_plus.dart';")
content.append("import 'package:dio/dio.dart';")
content.append("import 'package:flutter/material.dart';")
content.append("import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';")
content.append("import 'package:permission_handler/permission_handler.dart';")
content.append("import 'package:saver_gallery/saver_gallery.dart';")
content.append("")
content.append("class DownloadUtils {")
content.append("  static Future<bool> requestStoragePer() async {")
content.append("    await Permission.storage.request();")
content.append("    PermissionStatus status = await Permission.storage.status;")
content.append("    if (status == PermissionStatus.denied ||")
content.append("        status == PermissionStatus.permanentlyDenied) {")
content.append('      await permissionDialog("\u63d0\u793a", "\u5b58\u50a8\u6743\u9650\u672a\u83b7\u5f97");')
content.append("      return false;")
content.append("    } else {")
content.append("      return true;")
content.append("    }")
content.append("  }")
content.append("")
content.append("  static Future<bool> requestPhotoPer() async {")
content.append("    await Permission.photos.request();")
content.append("    PermissionStatus status = await Permission.photos.status;")
content.append("    if (status == PermissionStatus.denied ||")
content.append("        status == PermissionStatus.permanentlyDenied) {")
content.append('      await permissionDialog("\u63d0\u793a", "\u76f8\u518c\u6743\u9650\u672a\u83b7\u5f97");')
content.append("      return false;")
content.append("    } else {")
content.append("      return true;")
content.append("    }")
content.append("  }")
content.append("")
content.append("  static Future<bool> downloadImg(String imgUrl,")
content.append("      {String imgType = 'cover'}) async {")
content.append("    try {")
content.append("      if (Platform.isAndroid) {")
content.append("        final androidInfo = await DeviceInfoPlugin().androidInfo;")
content.append("        if (androidInfo.version.sdkInt <= 32) {")
content.append("          if (!await requestStoragePer()) {")
content.append("            return false;")
content.append("          }")
content.append("        } else {")
content.append("          if (!await requestPhotoPer()) {")
content.append("            return false;")
content.append("          }")
content.append("        }")
content.append("      }")
content.append("")
content.append("      if (Platform.isIOS) {")
content.append("        await requestPhotoPer();")
content.append("      }")
content.append("")
content.append('      SmartDialog.showLoading(msg: "\u4fdd\u5b58\u4e2d");')
content.append("      var response = await Dio()")
content.append("          .get(imgUrl, options: Options(responseType: ResponseType.bytes));")
content.append("      final String imgSuffix = imgUrl.split('.').last;")
content.append("      String picName =")
content.append('          "plpl_${imgType}_${DateTime.now().toString().replaceAll(RegExp(r\'[- :]\'), \'\').split(\'.\').first}";')
content.append("      final SaveResult result = await SaverGallery.saveImage(")
content.append("        Uint8List.fromList(response.data),")
content.append("        fileName: '\$picName.\$imgSuffix',")
content.append("        skipIfExists: false,")
content.append("      );")
content.append("      SmartDialog.dismiss();")
content.append("      if (result.isSuccess) {")
content.append('        SmartDialog.showToast("\u300a\$picName.\$imgSuffix\u300b\u5df2\u4fdd\u5b58");')
content.append("        return true;")
content.append("      } else {")
content.append('        await permissionDialog("\u4fdd\u5b58\u5931\u8d25", "\u76f8\u518c\u6743\u9650\u672a\u83b7\u5f97");')
content.append("        return false;")
content.append("      }")
content.append("    } catch (err) {")
content.append("      SmartDialog.dismiss();")
content.append("      SmartDialog.showToast(err.toString());")
content.append("      return false;")
content.append("    }")
content.append("  }")
content.append("")
content.append("  static Future permissionDialog(String title, String content,")
content.append("      {Function? onGranted}) async {")
content.append("    await SmartDialog.show(")
content.append("      useSystem: true,")
content.append("      animationType: SmartAnimationType.centerFade_otherSlide,")
content.append("      builder: (BuildContext context) {")
content.append("        return AlertDialog(")
content.append("          title: Text(title),")
content.append("          content: Text(content),")
content.append("          actions: [")
content.append("            TextButton(")
content.append("              onPressed: () async {")
content.append("                openAppSettings();")
content.append("              },")
content.append('              child: const Text("\u53bb\u8bbe\u7f6e"),')
content.append("            )")
content.append("          ],")
content.append("        );")
content.append("      },")
content.append("    );")
content.append("  }")
content.append("}")
content.append("")
with open(target, 'w', encoding='utf-8') as f:
    f.write('\n'.join(content))
print('done')
